[workspace]
members = [
    "tanoshi",
    "tanoshi-web",
    "tanoshi-lib"
]
default-members = ["tanoshi"]

[profile.release.package.tanoshi]
opt-level = 3

[profile.release.package.tanoshi-web]
opt-level = "s"