[package]
name = "tanoshi-lib"
version = "0.1.0"
authors = ["Muhammad Fadhlika <fadhlika@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["model", "mangadex", "extensions"]
model = []
mangadex = []
extensions = ["model"]

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_urlencoded = "0.6"
serde_derive = "1.0"
anyhow = "*"
chrono = { version = "0.4", features = ["serde"] }
human-sort = {version = "0.2"}
ureq = "1"

[build-dependencies]
rustc_version = "0.2"
