[package]
name = "tanoshi"
version = "0.1.0"
authors = ["fadhlika"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "*"
scraper = "*"
regex = "1"
serde_urlencoded = "*"
serde = { version = "*", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"

