[package]
name = "tanoshi-web"
version = "0.1.0"
authors = ["Muhammad Fadhlika <fadhlika@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "*", optional = true }
wee_alloc = { version = "*", optional = true }
yew = {version="0.14", features=["web_sys"]}
yew-router = {version="0.11", features=["web_sys"]}
failure = "*"
serde = "*"
serde_json ="1"
http = "*"
log = "*"
web_logger="*"
enclose = "*"
anyhow = "1.0.2"
quote = "=1.0.2"
js-sys = "*"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]


[dev-dependencies]
wasm-bindgen-test = "*"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true

