[package]
name = "tanoshi"
version = "0.1.0"
authors = ["fadhlika"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "0.11"
scraper = "0.11"
regex = "1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_urlencoded = "0.6"
serde_derive = "1.0"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
rust-argon2 = "0.8"
rand = "0.7"
sled = "0.31"
pretty_env_logger = "0.4"
jsonwebtoken = "7"
base64 = "0.12.0"
rusqlite = {version="0.21", features = ["serde_json", "chrono"]}
chrono = { version = "0.4", features = ["serde"] }
