[package]
name = "tanoshi-lib"
version = "0.25.3"
authors = ["Muhammad Fadhlika <fadhlika@gmail.com>"]
edition = "2018"
description = "Tanoshi library"
repository = "https://github.com/faldez/tanoshi"
license = "MIT"
readme = "README.md"
exclude = [".github/*"]

[dependencies]
thiserror = "1"
rquickjs = { git = "https://github.com/faldez/rquickjs", rev = "4f0a6eadb21ccc461b2aec83467a73852c480357", features = ["bindgen", "macro"] }
async-trait = "0.1.52"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
