[package]
name = "tanoshi-lib"
version = "0.26.0-beta.1"
authors = ["Muhammad Fadhlika <fadhlika@gmail.com>"]
edition = "2018"
description = "Tanoshi library"
repository = "https://github.com/faldez/tanoshi"
license = "MIT"
readme = "README.md"
exclude = [".github/*"]

[features]
default = ["js", "extension"]
js = ["rquickjs"]
extension = ["async-trait"]

[dependencies]
thiserror = "1"
rquickjs = { git = "https://github.com/faldez/rquickjs", features = [
    "bindgen",
    "macro",
], optional = true }
async-trait = { version = "0.1.52", optional = true }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
