[package]
name = "tanoshi-cli"
version = "0.4.9"
authors = ["Muhammad Fadhlika <fadhlika@gmail.com>"]
edition = "2018"
description = "Tanoshi CLI Utilities"
repository = "https://github.com/faldez/tanoshi"
license = "MIT"
readme = "README.md"
exclude = [".github/*"]

[dependencies]
tanoshi-lib = { path = "../tanoshi-lib", version = "0.25.1" }
tanoshi-vm = { path = "../tanoshi-vm", version = "0.5.6" }
serde_yaml = "0.8"
tokio = { version = "1", features = ["full"] }
clap = { version = "3.0.0-rc.5", features = ["derive"] }
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = { version = "0.4.14" }
env_logger = "0.9.0"
ureq = { version = "2", features = ["json"] }
rquickjs = { version = "0.1.4", features = [
    "full",
    "bindgen",
    "tokio",
    "futures",
    "parallel",
] }
