[package]
name = "tanoshi-vm"
version = "0.6.1"
authors = ["Muhammad Fadhlika <fadhlika@gmail.com>"]
edition = "2018"
description = "Tanoshi VM"
repository = "https://github.com/faldez/tanoshi"
license = "MIT"

[dependencies]
tanoshi-lib = { path = "../tanoshi-lib", version = "0.26.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
bytes = "1"
log = "0.4.14"
anyhow = "1"
flume = "0.10.9"
tokio = { version = "1", features = ["full"] }
rquickjs = { git = "https://github.com/faldez/rquickjs", features = [
    "full",
    "bindgen",
    "tokio",
    "futures",
    "parallel",
    "rust-alloc"
] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = [
    "cookies",
    "gzip",
    "brotli",
    "deflate",
    "json",
] }
pathdiff = "0.2.1"
async-trait = "0.1.52"
lazy_static = "1"
fnv = "1"

[dev-dependencies]
env_logger = "0.9.0"
