[package]
name = "tanoshi"
version = "0.25.20"
authors = ["fadhlika"]
edition = "2018"
description = "Tanoshi"
repository = "https://github.com/faldez/tanoshi"
license = "MIT"

[features]
default = ["embed", "server"]
embed = ["rust-embed"]
server = ["axum", "headers", "http", "async-graphql-axum"]

[dependencies]
tanoshi-lib = { path = "../tanoshi-lib" }
tanoshi-vm = { path = "../tanoshi-vm", default-features = false }
tokio = { version = "1", features = ["full"] }
tokio-stream = "^0.1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
async-graphql = { version = "^2.10.0", features = [
    "apollo_tracing",
    "chrono",
    "dataloader",
] }
async-graphql-axum = { version = "^2.10.0", optional = true }
axum = { version = "=0.2.5", features = ["headers"], optional = true }
headers = { version = "0.3", optional = true }
http = { version = "0.2.5", optional = true }
rand = { version = "^0.8" }
log = { version = "*" }
env_logger = "0.9.0"
jsonwebtoken = { version = "7" }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1"
rust-embed = { version = "6.0", features = [
    "interpolate-folder-path",
], optional = true }
mime_guess = "2"
clap = "=3.0.0-beta.5"
bytes = "1"
dirs = "4"
base64 = "0.13"
sqlx = { version = "^0.5.9", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "chrono",
    "json",
    "migrate",
] }
reqwest = { version = "^0.11.4", features = ["json"] }
futures = "^0.3"
rust-argon2 = "^0.8.3"
ron = "^0.6.5"
fancy-regex = "0.7"
compress-tools = { git = "https://github.com/faldez/compress-tools-rs", features = [
    "static",
] }
zip = { version = "0.5", default-features = false }
teloxide = { version = "^0.5.2", features = ["auto-send", "macros"] }
html-escape = "^0.2.9"
phf = { version = "^0.10", features = ["macros"] }
human-sort = "^0.2.2"
aes = "^0.7.5"
block-modes = "^0.8.1"
once_cell = "^1.8.0"
async-trait = "^0.1.51"
portpicker = "0.1"
