[package]
name = "tanoshi"
version = "0.3.0"
authors = ["fadhlika"]
edition = "2018"

[dependencies]
tanoshi-lib = {git = "https://github.com/fadhlika/tanoshi-lib", branch = "master", features = ["extensions", "model"]}
ureq = {version = "1"}
scraper = {version = "0.12"}
fancy-regex = {version = "0.3"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_urlencoded = "0.6"
serde_derive = "1.0"
tokio = { version = "0.2", features = ["full"] }
warp = {version = "0.2", features = ["compression"]}
rust-argon2 = {version = "0.8"}
rand = {version = "0.7"}
log = {version = "*"}
pretty_env_logger = {version = "0.4"}
jsonwebtoken = {version = "7"}
sqlx = { version = "0.3", default-features = false, features = [ "runtime-tokio", "macros", "chrono", "postgres", "tls"] }
chrono = { version = "0.4", features = ["serde"] }
futures = {version = "*"}
human-sort = {version = "0.2"}
zip = {version = "0.5"}
anyhow = "1"
libloading = {version = "0.6"}
rust-embed= {version="5.5.1"}
mime_guess = "2"