[package]
name = "tanoshi"
version = "0.1.0"
authors = ["fadhlika"]
edition = "2018"

[lib]
crate-type = ["lib"]

[features]
bin = [
    "ureq",
    "scraper",
    "regex",
    "tokio",
    "warp",
    "rust-argon2",
    "rand",
    "pretty_env_logger",
    "jsonwebtoken",
    "base64",
    "sqlx",
    "futures",
]
lib = []

[dependencies]
ureq = {version = "0.11", optional = true}
scraper = {version = "0.11", optional = true}
regex = {version = "1", optional = true}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_urlencoded = "0.6"
serde_derive = "1.0"
tokio = { version = "0.2", features = ["macros"], optional = true }
warp = {version = "0.2", optional = true}
rust-argon2 = {version = "0.8", optional = true}
rand = {version = "0.7", optional = true}
pretty_env_logger = {version = "0.4", optional = true}
jsonwebtoken = {version = "7", optional = true}
base64 = {version = "0.12.0", optional = true}
sqlx = { version = "0.3", default-features = false, features = [ "runtime-tokio", "macros", "chrono", "postgres", "tls"], optional = true }
chrono = { version = "0.4", features = ["serde"] }
futures = {version = "*", optional = true}
human-sort = {version = "0.2"}