name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend
        run: cd $GITHUB_WORKSPACE/tanoshi-web && yarn install && cargo install wasm-bindgen-cli wasm-pack && yarn build
      - name: Build Backend
        run: cd $GITHUB_WORKSPACE/tanoshi && cargo build
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend
        run: cd $GITHUB_WORKSPACE/tanoshi-web && yarn install && cargo install wasm-bindgen-cli wasm-pack && yarn build
      - name: Build Backend
        run: cd $GITHUB_WORKSPACE/tanoshi && cargo build
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend
        run: cd $Env:GITHUB_WORKSPACE\tanoshi-web -and yarn install -and cargo install wasm-bindgen-cli wasm-pack -and yarn build
      - name: Build Backend
        run: cd $Env:GITHUB_WORKSPACE\tanoshi -and cargo build
      - name: List
        run: ls -l $Env:GITHUB_WORKSPACE
      - name: List Target
        run: ls -l $Env:GITHUB_WORKSPACE\target
      - name: List Release
        run: ls -l $Env:GITHUB_WORKSPACE\target\release
