name: check

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "**/README.md"
      - "screenshots/**"
      - .github/**

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: cargo install wasm-bindgen-cli wasm-pack
      - name: Build Frontend
        run: cd $GITHUB_WORKSPACE/tanoshi-web && yarn install && yarn build
      - name: Build Backend
        run: cd $GITHUB_WORKSPACE && cargo check -p tanoshi
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: cargo install wasm-bindgen-cli wasm-pack
      - name: Build Frontend
        run: cd $GITHUB_WORKSPACE/tanoshi-web && yarn install && yarn build
      - name: Build Backend
        run: cd $GITHUB_WORKSPACE && cargo check -p tanoshi
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: cargo install wasm-bindgen-cli wasm-pack
      - name: Build Frontend
        run: cd $Env:GITHUB_WORKSPACE/tanoshi-web && yarn install && yarn build
      - name: Build Backend
        run: cd $Env:GITHUB_WORKSPACE && cargo check -p tanoshi
