name: check

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "**/README.md"
      - .github/screenshots/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            filename: tanoshi
          - os: macos-latest
            filename: tanoshi
          - os: windows-latest
            filename: tanoshi.exe
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt update && sudo apt install -y libssl-dev libarchive-dev build-essential cmake llvm clang libicu-dev nettle-dev libacl1-dev liblzma-dev libzstd-dev liblz4-dev libbz2-dev zlib1g-dev libxml2-dev
      - name: Install deps
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install icu4c libarchive bzip2 lz4 zlib expat
      - name: Install LLVM and Clang
        if: ${{ matrix.os == 'windows-latest' }}
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0"
      - name: Install deps
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          vcpkg integrate install
          vcpkg install --only-downloads libarchive:x64-windows-static-md
          vcpkg install libarchive:x64-windows-static-md
      - name: Install trunk
        run: cargo install trunk
      - name: Build tanoshi-web
        run: trunk build
      - name: Build tanoshi
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cargo build -p tanoshi
      - name: Build tanoshi
        if: ${{ matrix.os == 'macos-latest' }}
        run: cargo build -p tanoshi
        env:
          PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig
      - name: Build tanoshi
        if: ${{ matrix.os == 'windows-latest' }}
        run: cargo build -p tanoshi
        env:
          LIBCLANG_PATH: C:\Program Files\LLVM\bin
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.filename }}
          path: ${{ github.workspace }}/target/debug/${{ matrix.filename }}
          retention-days: 7
