name: test

on:
  pull_request:
    paths:
      - crates/**
      - "!**/*.md"
      - "!.github/screenshots/**"
  push:
    branches: [master]
    paths:
      - .github/workflows/master.yml
      - Dockerfile
      - crates/**
      - "!**/*.md"
      - "!.github/screenshots/**"

jobs:
  build-docker:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: faldez/tanoshi:master
          build-args: |
            BUILD_WEB=false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir crates/tanoshi-web/dist
      - name: Install deps
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt update && sudo apt upgrade -y && sudo apt install -y libssl-dev libarchive-dev build-essential cmake llvm clang libicu-dev nettle-dev libacl1-dev liblzma-dev libzstd-dev liblz4-dev libbz2-dev zlib1g-dev libxml2-dev lsb-release wget software-properties-common libwebkit2gtk-4.0-dev curl libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libpango1.0-dev
      - name: Install deps
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install icu4c libarchive bzip2 lz4 zlib expat llvm@11
      - name: Install LLVM and Clang
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
      - name: Install LLVM and Clang
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Invoke-WebRequest -Uri https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/LLVM-11.0.1-win64.exe -OutFile LLVM-11.0.1-win64.exe
          7z x .\LLVM-11.0.1-win64.exe -aoa -o'C:\Program Files\LLVM'
      - name: Download LLVM
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Invoke-WebRequest -Uri https://github.com/faldez/tanoshi-builder/releases/download/v0.1.0/LLVM.7z -OutFile LLVM.7z
          7z x .\LLVM.7z -o'C:\'
      - name: Cache vcpkg
        uses: actions/cache@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          path: "C:/vcpkg/installed"
          key: vcpkg-${{ matrix.os }}-
          restore-keys: |
            vcpkg-${{ matrix.os }}-
      - name: Install deps
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          vcpkg integrate install
          vcpkg install --only-downloads libarchive:x64-windows-static-md
          vcpkg install libarchive:x64-windows-static-md
      - name: Test
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUSTFLAGS: "-Clink-arg=-Wl,--allow-multiple-definition"
          LLVM_SYS_110_PREFIX: ${{ env.LLVM_PATH }}
      - name: Test
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/expat/lib/pkgconfig
          LLVM_SYS_110_PREFIX: /usr/local/opt/llvm
      - name: Test
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          LLVM_SYS_110_PREFIX: C:\LLVM
          LIBCLANG_PATH: C:\Program Files\LLVM\bin
