name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: tanoshi
          POSTGRES_PASSWORD: tanoshi
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - /docker-entrypoint-initdb.d:tanoshi/migration

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      env:
          # The hostname used to communicate with the PostgreSQL service container
          DATABASE_URL: postgres://tanoshi:tanoshi@postgres:5432/tanoshi
